### ISSUE TITLE
Link to the API

### ISSUE THREAD

**Issue by JusterLuk** [rstropek-teaching/product-catalog-quiz-5ahif-JusterLuk#1]
http://productcatalogmvc20171206121054.azurewebsites.net/

**Comment by rstropek** [comment]
@JusterLuk Thank you for the link. It works as expected. However, you did not checkin any source code. Probably a problem with Git. If you checkin your code, your extra point would be secured.

Greetings,
Rainer Stropek.

**Comment by JusterLuk** [comment]
the Code should be here now

**Comment by rstropek** [comment]
Great, thank you.

Greetings,
Rainer Stropek.
